name: Daily News Fetch

on:
  schedule:
    - cron: '0 9 * * *'    # every day at 9:00 UTC
  workflow_dispatch:       # also allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # or your preferred version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests newspaper3k supabase
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python search_trends.py
